[ ERROR ] 241 Internal Server Error: /
Traceback (most recent call last):
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: silk_request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/silk/middleware.py", line 70, in __call__
    self.process_request(request)
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/silk/middleware.py", line 120, in process_request
    request_model = RequestModelFactory(request).construct_request_model()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/silk/model_factory.py", line 243, in construct_request_model
    request_model = models.Request.objects.create(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/silk/models.py", line 190, in save
    super().save(*args, **kwargs)
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanp/VSCodeProjects/hello-python-on-steroids/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: silk_request
[ ERROR ] 241 Internal Server Error: /api/exception/
